version: "3.8"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
      POSTGRES_DB: stockpot
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  migrate:
    build:
      context: ..
      dockerfile: build/api.dockerfile
    entrypoint: sh -c "./stockpot --config configs/stockpot.yaml migrate"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
        restart: true

  api:
    build:
      context: ..
      dockerfile: build/api.dockerfile
    container_name: api
    env_file:
      - .env
    depends_on:
      migrate:
        condition: service_completed_successfully

  frontend:
    build:
      context: ..
      dockerfile: build/frontend.dockerfile
    env_file:
      - .env

  reverse-proxy:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ../build/files/reverse-proxy.nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - frontend

networks:
  app:
    driver: bridge

volumes:
  postgres:
