// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"
)

const createAuthUser = `-- name: CreateAuthUser :one
INSERT INTO auth_user (username, password_hash, app_user) values ($1, $2, $3) RETURNING id, username, password_hash, app_user
`

type CreateAuthUserParams struct {
	Username     string
	PasswordHash string
	AppUser      int64
}

func (q *Queries) CreateAuthUser(ctx context.Context, arg CreateAuthUserParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, createAuthUser, arg.Username, arg.PasswordHash, arg.AppUser)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.AppUser,
	)
	return i, err
}

const getAuthUser = `-- name: GetAuthUser :one
SELECT id, username, password_hash, app_user FROM auth_user WHERE username = $1 LIMIT 1
`

func (q *Queries) GetAuthUser(ctx context.Context, username string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getAuthUser, username)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.AppUser,
	)
	return i, err
}
