// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRecipe = `-- name: DeleteRecipe :exec
DELETE FROM recipe
WHERE id = $1
`

func (q *Queries) DeleteRecipe(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteRecipe, id)
	return err
}

const deleteRecipeIngredients = `-- name: DeleteRecipeIngredients :exec
DELETE FROM recipe_ingredient
WHERE recipe = $1 AND id != ALL($2::bigint[])
`

type DeleteRecipeIngredientsParams struct {
	Recipe        int64
	IngredientIds []int64
}

func (q *Queries) DeleteRecipeIngredients(ctx context.Context, arg DeleteRecipeIngredientsParams) error {
	_, err := q.db.Exec(ctx, deleteRecipeIngredients, arg.Recipe, arg.IngredientIds)
	return err
}

const deleteSteps = `-- name: DeleteSteps :exec
DELETE FROM step
WHERE recipe = $1 AND id != ALL($2::bigint[])
`

type DeleteStepsParams struct {
	Recipe  int64
	StepIds []int64
}

func (q *Queries) DeleteSteps(ctx context.Context, arg DeleteStepsParams) error {
	_, err := q.db.Exec(ctx, deleteSteps, arg.Recipe, arg.StepIds)
	return err
}

const getAllRecipeIngredients = `-- name: GetAllRecipeIngredients :many
SELECT
    ri.id,
    ri.recipe,
    i.id, i.name,
    ri.quantity,
    riu.id, riu.name,
    ri.preparation
FROM recipe_ingredient ri
JOIN ingredient i ON i.id = ri.ingredient
JOIN unit riu ON ri.units = riu.id
`

type GetAllRecipeIngredientsRow struct {
	ID          int64
	Recipe      int64
	Ingredient  Ingredient
	Quantity    int32
	Unit        Unit
	Preparation string
}

func (q *Queries) GetAllRecipeIngredients(ctx context.Context) ([]GetAllRecipeIngredientsRow, error) {
	rows, err := q.db.Query(ctx, getAllRecipeIngredients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllRecipeIngredientsRow
	for rows.Next() {
		var i GetAllRecipeIngredientsRow
		if err := rows.Scan(
			&i.ID,
			&i.Recipe,
			&i.Ingredient.ID,
			&i.Ingredient.Name,
			&i.Quantity,
			&i.Unit.ID,
			&i.Unit.Name,
			&i.Preparation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllRecipeSteps = `-- name: GetAllRecipeSteps :many
SELECT
    s.id,
    s.recipe,
    s.ordinal,
    s.instruction
FROM step s
`

func (q *Queries) GetAllRecipeSteps(ctx context.Context) ([]Step, error) {
	rows, err := q.db.Query(ctx, getAllRecipeSteps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Step
	for rows.Next() {
		var i Step
		if err := rows.Scan(
			&i.ID,
			&i.Recipe,
			&i.Ordinal,
			&i.Instruction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecipe = `-- name: GetRecipe :one
SELECT
    r.id as id,
    r.title as title,
    r.description as description,
    au.id, au.name,
    EXTRACT(EPOCH FROM r.prep_time)::bigint_nullable as prep_time,
    EXTRACT(EPOCH FROM r.cook_time)::bigint_nullable as cook_time,
    EXTRACT(EPOCH FROM r.inactive_time)::bigint_nullable as inactive_time,
    r.yield_quantity as yield_quantity,
    ru.id, ru.name
FROM
    recipe AS r
    JOIN app_user au ON r.author = au.id
    JOIN unit ru ON r.yield_units = ru.id
WHERE r.id = $1
`

type GetRecipeRow struct {
	ID            int64
	Title         string
	Description   pgtype.Text
	AppUser       AppUser
	PrepTime      pgtype.Numeric
	CookTime      pgtype.Numeric
	InactiveTime  pgtype.Numeric
	YieldQuantity int32
	Unit          Unit
}

func (q *Queries) GetRecipe(ctx context.Context, id int64) (GetRecipeRow, error) {
	row := q.db.QueryRow(ctx, getRecipe, id)
	var i GetRecipeRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.AppUser.ID,
		&i.AppUser.Name,
		&i.PrepTime,
		&i.CookTime,
		&i.InactiveTime,
		&i.YieldQuantity,
		&i.Unit.ID,
		&i.Unit.Name,
	)
	return i, err
}

const getRecipeIngredients = `-- name: GetRecipeIngredients :many
SELECT
    ri.id,
    ri.recipe,
    i.id, i.name,
    ri.quantity,
    riu.id, riu.name,
    ri.preparation
FROM recipe_ingredient ri
JOIN ingredient i ON i.id = ri.ingredient
JOIN unit riu ON ri.units = riu.id
WHERE ri.recipe = $1
`

type GetRecipeIngredientsRow struct {
	ID          int64
	Recipe      int64
	Ingredient  Ingredient
	Quantity    int32
	Unit        Unit
	Preparation string
}

func (q *Queries) GetRecipeIngredients(ctx context.Context, recipe int64) ([]GetRecipeIngredientsRow, error) {
	rows, err := q.db.Query(ctx, getRecipeIngredients, recipe)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecipeIngredientsRow
	for rows.Next() {
		var i GetRecipeIngredientsRow
		if err := rows.Scan(
			&i.ID,
			&i.Recipe,
			&i.Ingredient.ID,
			&i.Ingredient.Name,
			&i.Quantity,
			&i.Unit.ID,
			&i.Unit.Name,
			&i.Preparation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecipeSteps = `-- name: GetRecipeSteps :many
SELECT
    s.id,
    s.recipe,
    s.ordinal,
    s.instruction
FROM step s
WHERE s.recipe = $1
`

func (q *Queries) GetRecipeSteps(ctx context.Context, recipe int64) ([]Step, error) {
	rows, err := q.db.Query(ctx, getRecipeSteps, recipe)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Step
	for rows.Next() {
		var i Step
		if err := rows.Scan(
			&i.ID,
			&i.Recipe,
			&i.Ordinal,
			&i.Instruction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecipes = `-- name: GetRecipes :many
SELECT
    r.id as id,
    r.title as title,
    r.description as description,
    au.id, au.name,
    EXTRACT(EPOCH FROM r.prep_time)::bigint_nullable as prep_time,
    EXTRACT(EPOCH FROM r.cook_time)::bigint_nullable as cook_time,
    EXTRACT(EPOCH FROM r.inactive_time)::bigint_nullable as inactive_time,
    r.yield_quantity as yield_quantity,
    ru.id, ru.name
FROM
    recipe AS r
    JOIN app_user au ON r.author = au.id
    JOIN unit ru ON r.yield_units = ru.id
`

type GetRecipesRow struct {
	ID            int64
	Title         string
	Description   pgtype.Text
	AppUser       AppUser
	PrepTime      pgtype.Numeric
	CookTime      pgtype.Numeric
	InactiveTime  pgtype.Numeric
	YieldQuantity int32
	Unit          Unit
}

func (q *Queries) GetRecipes(ctx context.Context) ([]GetRecipesRow, error) {
	rows, err := q.db.Query(ctx, getRecipes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecipesRow
	for rows.Next() {
		var i GetRecipesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.AppUser.ID,
			&i.AppUser.Name,
			&i.PrepTime,
			&i.CookTime,
			&i.InactiveTime,
			&i.YieldQuantity,
			&i.Unit.ID,
			&i.Unit.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertIngredients = `-- name: InsertIngredients :many
INSERT INTO ingredient (name) 
SELECT i.name
FROM unnest(
    $1::text[]
) AS i(name)
ON CONFLICT (name) DO NOTHING RETURNING id, name
`

func (q *Queries) InsertIngredients(ctx context.Context, names []string) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, insertIngredients, names)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingredient
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRecipe = `-- name: InsertRecipe :one
INSERT INTO recipe (
    title,
    description,
    author,
    prep_time,
    cook_time,
    inactive_time,
    yield_quantity,
    yield_units
) VALUES ($1, $2, $3, $4, $5, $6, $7, (SELECT id FROM unit WHERE name = $8))
RETURNING id, title, description, author, prep_time, cook_time, inactive_time, yield_quantity, yield_units
`

type InsertRecipeParams struct {
	Title          string
	Description    pgtype.Text
	Author         int64
	PrepTime       pgtype.Interval
	CookTime       pgtype.Interval
	InactiveTime   pgtype.Interval
	YieldQuantity  int32
	YieldUnitsName string
}

func (q *Queries) InsertRecipe(ctx context.Context, arg InsertRecipeParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, insertRecipe,
		arg.Title,
		arg.Description,
		arg.Author,
		arg.PrepTime,
		arg.CookTime,
		arg.InactiveTime,
		arg.YieldQuantity,
		arg.YieldUnitsName,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Author,
		&i.PrepTime,
		&i.CookTime,
		&i.InactiveTime,
		&i.YieldQuantity,
		&i.YieldUnits,
	)
	return i, err
}

const insertRecipeIngredients = `-- name: InsertRecipeIngredients :many
INSERT INTO recipe_ingredient (recipe, ingredient, quantity, units, preparation) 
SELECT 
    unnest($1::bigint[]) as recipe_id,
    unnest(ARRAY(SELECT i.id FROM unnest($2::text[]) as n(ingredient_name) JOIN ingredient i ON n.ingredient_name = i.name)) as ingredient_id,
    unnest($3::integer[]) as quantity,
    unnest(ARRAY(SELECT u.id FROM unnest($4::text[]) as n(unit_name) JOIN unit u ON n.unit_name = u.name)) as unit_id,
    unnest($5::text[]) as preparation
RETURNING id, recipe, ingredient, quantity, units, preparation
`

type InsertRecipeIngredientsParams struct {
	RecipeIds       []int64
	IngredientNames []string
	Quantities      []int32
	UnitNames       []string
	Preparations    []string
}

func (q *Queries) InsertRecipeIngredients(ctx context.Context, arg InsertRecipeIngredientsParams) ([]RecipeIngredient, error) {
	rows, err := q.db.Query(ctx, insertRecipeIngredients,
		arg.RecipeIds,
		arg.IngredientNames,
		arg.Quantities,
		arg.UnitNames,
		arg.Preparations,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecipeIngredient
	for rows.Next() {
		var i RecipeIngredient
		if err := rows.Scan(
			&i.ID,
			&i.Recipe,
			&i.Ingredient,
			&i.Quantity,
			&i.Units,
			&i.Preparation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSteps = `-- name: InsertSteps :many
INSERT INTO step (recipe, ordinal, instruction) 
SELECT 
    unnest($1::bigint[]) as recipe_id,
    unnest($2::integer[]) as ordinal,
    unnest($3::text[]) as instruction
RETURNING id, recipe, ordinal, instruction
`

type InsertStepsParams struct {
	RecipeIds    []int64
	Ordinals     []int32
	Instructions []string
}

func (q *Queries) InsertSteps(ctx context.Context, arg InsertStepsParams) ([]Step, error) {
	rows, err := q.db.Query(ctx, insertSteps, arg.RecipeIds, arg.Ordinals, arg.Instructions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Step
	for rows.Next() {
		var i Step
		if err := rows.Scan(
			&i.ID,
			&i.Recipe,
			&i.Ordinal,
			&i.Instruction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRecipe = `-- name: UpsertRecipe :one
INSERT INTO recipe (
    id,
    title,
    description,
    author,
    prep_time,
    cook_time,
    inactive_time,
    yield_quantity,
    yield_units
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, (SELECT id FROM unit WHERE name = $9))
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    author = EXCLUDED.author,
    prep_time = EXCLUDED.prep_time,
    cook_time = EXCLUDED.cook_time,
    inactive_time = EXCLUDED.inactive_time,
    yield_quantity = EXCLUDED.yield_quantity,
    yield_units = EXCLUDED.yield_units
RETURNING id, title, description, author, prep_time, cook_time, inactive_time, yield_quantity, yield_units
`

type UpsertRecipeParams struct {
	ID             int64
	Title          string
	Description    pgtype.Text
	Author         int64
	PrepTime       pgtype.Interval
	CookTime       pgtype.Interval
	InactiveTime   pgtype.Interval
	YieldQuantity  int32
	YieldUnitsName string
}

func (q *Queries) UpsertRecipe(ctx context.Context, arg UpsertRecipeParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, upsertRecipe,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Author,
		arg.PrepTime,
		arg.CookTime,
		arg.InactiveTime,
		arg.YieldQuantity,
		arg.YieldUnitsName,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Author,
		&i.PrepTime,
		&i.CookTime,
		&i.InactiveTime,
		&i.YieldQuantity,
		&i.YieldUnits,
	)
	return i, err
}

const upsertRecipeIngredients = `-- name: UpsertRecipeIngredients :many
INSERT INTO recipe_ingredient (id, recipe, ingredient, quantity, units, preparation) 
SELECT 
    unnest($1::bigint[]) as id,
    unnest($2::bigint[]) as recipe_id,
    unnest(ARRAY(SELECT i.id FROM unnest($3::text[]) as n(ingredient_name) JOIN ingredient i ON n.ingredient_name = i.name)) as ingredient_id,
    unnest($4::integer[]) as quantity,
    unnest(ARRAY(SELECT u.id FROM unnest($5::text[]) as n(unit_name) JOIN unit u ON n.unit_name = u.name)) as unit_id,
    unnest($6::text[]) as preparation
ON CONFLICT (id) DO UPDATE SET
    recipe = EXCLUDED.recipe,
    ingredient = EXCLUDED.ingredient,
    quantity = EXCLUDED.quantity,
    units = EXCLUDED.units,
    preparation = EXCLUDED.preparation
RETURNING id, recipe, ingredient, quantity, units, preparation
`

type UpsertRecipeIngredientsParams struct {
	Ids             []int64
	RecipeIds       []int64
	IngredientNames []string
	Quantities      []int32
	UnitNames       []string
	Preparations    []string
}

func (q *Queries) UpsertRecipeIngredients(ctx context.Context, arg UpsertRecipeIngredientsParams) ([]RecipeIngredient, error) {
	rows, err := q.db.Query(ctx, upsertRecipeIngredients,
		arg.Ids,
		arg.RecipeIds,
		arg.IngredientNames,
		arg.Quantities,
		arg.UnitNames,
		arg.Preparations,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecipeIngredient
	for rows.Next() {
		var i RecipeIngredient
		if err := rows.Scan(
			&i.ID,
			&i.Recipe,
			&i.Ingredient,
			&i.Quantity,
			&i.Units,
			&i.Preparation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSteps = `-- name: UpsertSteps :many
INSERT INTO step (id, recipe, ordinal, instruction) 
SELECT 
    unnest($1::bigint[]) as id,
    unnest($2::bigint[]) as recipe_id,
    unnest($3::integer[]) as ordinal,
    unnest($4::text[]) as instruction
ON CONFLICT (id) DO UPDATE SET
    recipe = EXCLUDED.recipe,
    ordinal = EXCLUDED.ordinal,
    instruction = EXCLUDED.instruction
RETURNING id, recipe, ordinal, instruction
`

type UpsertStepsParams struct {
	Ids          []int64
	RecipeIds    []int64
	Ordinals     []int32
	Instructions []string
}

func (q *Queries) UpsertSteps(ctx context.Context, arg UpsertStepsParams) ([]Step, error) {
	rows, err := q.db.Query(ctx, upsertSteps,
		arg.Ids,
		arg.RecipeIds,
		arg.Ordinals,
		arg.Instructions,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Step
	for rows.Next() {
		var i Step
		if err := rows.Scan(
			&i.ID,
			&i.Recipe,
			&i.Ordinal,
			&i.Instruction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
