// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const createAppUser = `-- name: CreateAppUser :one
INSERT INTO app_user (name) values ($1) RETURNING id, name
`

func (q *Queries) CreateAppUser(ctx context.Context, name string) (AppUser, error) {
	row := q.db.QueryRow(ctx, createAppUser, name)
	var i AppUser
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getAppUser = `-- name: GetAppUser :one
SELECT id, name FROM app_user WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAppUser(ctx context.Context, id int64) (AppUser, error) {
	row := q.db.QueryRow(ctx, getAppUser, id)
	var i AppUser
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
