version: "3.8"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
      POSTGRES_DB: stockpot
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  migrate:
    image: ghcr.io/mthstanley/stockpot-api:local
    entrypoint: sh -c "./stockpot --config configs/stockpot.yaml migrate"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
        restart: true

  api:
    image: ghcr.io/mthstanley/stockpot-api:local
    restart: unless-stopped
    container_name: api
    env_file:
      - .env
    depends_on:
      migrate:
        condition: service_completed_successfully

  frontend:
    image: ghcr.io/mthstanley/stockpot-frontend:local
    restart: unless-stopped
    env_file:
      - .env

  reverse-proxy:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/:/etc/nginx/:ro
      - ./certbot/www/:/var/www/certbot/:ro
    depends_on:
      - api
      - frontend

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

networks:
  app:
    driver: bridge

volumes:
  postgres:
